name: Publish Release Binaries

on:
  push:
    branches: [main]
    paths: ["src/**", "Cargo.toml", "Cargo.lock"]
  # pull_request:
  #   branches: [main]

env:
  BINARY_NAME: reddit_clawler
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo build --release --all

      - name: Set short sha
        id: set-short-sha
        run: echo "SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Extract package version
        id: set-package-version
        run: echo "PKG_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')" >> $GITHUB_OUTPUT

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./target/release/${{ env.BINARY_NAME }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          asset_name: ${{ env.BINARY_NAME }}-${{ matrix.os }}
          tag: "v${{ steps.set-package-version.outputs.PKG_VERSION }}-${{ steps.set-short-sha.outputs.SHA }}"
